spring.application.name=votacao

spring.datasource.url=jdbc:postgresql://localhost:5432/votacao
spring.datasource.username=votacao
spring.datasource.password=votacao

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jackson.default-property-inclusion=non_null

springdoc.swagger-ui.path=/swagger-ui.html

app.base-url=${APP_BASE_URL:http://localhost:8080}
app.sessao.duracao-padrao-segundos=60

logging.level.com.assembleia.votacao=DEBUG
